# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.
# More information: https://docs.platform.sh/add-services.html
# Full list of available services: https://docs.platform.sh/add-services.html#available-services
postgresql:
  type: postgresql:15 # All available versions are: 15, 14, 13, 12, 11
  disk: 1024 # All available sizes are: 1024, 2048, 3072, 4096, 5120
redis:
  type: redis:7.0 # All available versions are: 7.0, 6.2